language: node_js
node_js:
 - "stable"

install: 
- npm install -g codecov
- npm install

services:
  - postgresql
env:
  global:
    - NODE_ENV=test
    - CC_TEST_REPORTER_ID=c9d52ceca858b7b11e56c67dc50e2d6c069a4be7e0c40ca6aceee8d674b65fd7
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script: yarn test

after_success:
  - yarn run coverage
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT